### PR TITLE
Added getting metadata from a note id

### PR DESCRIPTION
**Pull request by darkdecoy**
Added getting metadata from a note id

### CODE REVIEW

**Comment by pirate** [comment]
This is a good addition, thanks!


Out of curiosity why filter the metadata with jq? I think it makes more sense to return all the json that the endpoint returns and let the user pipe it into jq after if they need to filter it.

**Comment by darkdecoy** [comment]
I used it for more formatting than actually formatting  as it allowed to return the metadata in a bash array rather than json which found to more useful for and easier to process in the script that I was writing.

**Comment by darkdecoy** [comment]
An option to return it in json instead could be added like history command

**Comment by ErikMichelson** [comment]
Please consider adding the syntax to the usage/help information (which is displayed when calling the script without further arguments)

**Pull request closed without merging**
